### ISSUE TITLE
No link to issue tracker on website

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-milagro#19]
I could not find a link to the issue tracker on the website.

I'm hoping this is it...

Please ensure that it is easy to find the issue tracker from the website

**Comment by JohnMcW** [comment]
@sebbASF - I've added an "issues" section here: milagro.apache.org/docs/contributor-guide/
 including links to our GitHub repos.  Please let me know if that' sufficient.  

Also, are you by any chance a moderator of announce@apache.org?  I couldn't help noticing you'd raised these two issues shortly after I sent the email, then noticed the email was approved right after we'd made these two fixes.  If so, then thanks!  If not, then thanks anyway!

**Comment by sebbASF** [comment]
Might be an idea to add a link to the Support page as well.

**Comment by JohnMcW** [comment]
@sebbASF - I've updated the support page to include an "issues" section - please can you confirm this is OK, and I'll close this?

**Comment by sebbASF** [comment]
It would be nice if the user did not have to click so many times to get to the issue tracker.

Currently the route from the main page is:
- click "Support"
- read the Issues para, and click "Contributing"
- scan the "Issues" para and click the appropriate link
- click the Issues tab

Obviously it's not possible to have a one-click link, as there are several issue trackers, but some of the stages could be eliminated.

One can go straight to "Contributing" from the main page, but if I am looking to report a bug, I would normally expect to find the instructions under "Support" rather than "Contributing"

Might be nice to have direct link to issues section on front page
Also could link directly to issues tab on Contributing page.

Another possibility would be to have a separate Issue handling page.
This could be linked from Support, Contributing and the Home page.

**Comment by JohnMcW** [comment]
Hi @sebbASF  - I've updated the support page with direct links to each repo's issue page

**Comment by sebbASF** [comment]
Thanks, makes it easier to find the trackers
