### ISSUE TITLE
Mangled sentence

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-milagro#20]
The page http://milagro.apache.org/docs/milagro-intro/ has the following sentence:

"In certain use cases, this removes the need for a PKI infrastructure eliminates the root key 'single point of compromise' weakness, as the main reason to issue certificates is used to bind a public / private key pair to an identity."

This does not read well - maybe some missing words?
Probably should be split into multiple sentences.

**Comment by JohnMcW** [comment]
@sebbASF - we've addressed this issue - please let me know if it's OK?

**Comment by sebbASF** [comment]
It's better, but still a bit hard to read.

The following phrase:

"the need for a PKI infrastructure as the main reason to issue certificates"

would read better as

"the need for a PKI infrastructure, since the main reason to issue certificates"

As it stands, the "as" clause is ambiguous.
It could be taken in the sense of "Using another system as a backup".
The word "since" does not have that double meaning, and the comma helps too.

**Comment by JohnMcW** [comment]
@sebbASF - this is now done - please can you confirm?

**Comment by sebbASF** [comment]
That reads better, thanks.

Just notice that the first sentence says:

"Apache Milagro is core security infrastructure and crypto libraries"

I suspect that should be something like:

"Apache Milagro is a set of core security infrastructure and crypto libraries

**Comment by JohnMcW** [comment]
@sebbASF - done.  Please can you confirm and I'll close this issue?

**Comment by sebbASF** [comment]
Reads much better, thanks
