### ISSUE TITLE
Web/documentation needs refresh

### ISSUE THREAD

**Issue by JohnMcW** [apache/incubator-milagro#6]
Milagro, in all aspects, needs a refresh. The project website and documentation sites are both horribly out of date. For the proposal, go to https://cwiki.apache.org/confluence/display/MILAGRO/Home

**Comment by JohnMcW** [comment]
Was issue https://issues.apache.org/jira/browse/MILAGRO-27 in Apache Jira (this issue will be closed presently)

**Comment by spector-in-london** [comment]
Let's close issue.
